server:
  #访问端口
  port: 8080
  servlet:
    #访问路径
    context-path: /question
spring:
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 60000
#mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.heu.domain
  config-location: classpath:mybatis/mybatis-config.xml
#pageHelper分页插件
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

